In [1]:
import numpy as np

# 50 method of numpy      Roll no:PIAIC149041

In [2]:
a = np.array([1, 2, 3])
np.zeros(2)

array([0., 0.])

In [3]:
np.ones(2)

array([1., 1.])

In [4]:
np.empty(2)

array([1., 1.])

In [5]:
np.arange(4)

array([0, 1, 2, 3])

In [6]:
np.arange(2, 9, 2)

array([2, 4, 6, 8])

In [7]:
np.linspace(0, 10, num=5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [8]:
x = np.ones(2, dtype=np.int64)
x

array([1, 1], dtype=int64)

In [9]:
arr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [10]:
np.searchsorted(arr)

TypeError: _searchsorted_dispatcher() missing 1 required positional argument: 'v'

In [11]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [12]:
array_example = np.array([[[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                           [[0, 1, 2, 3],
                            [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                            [4, 5, 6, 7]]])
array_example.ndim

3

In [13]:
array_example.size

24

In [14]:
array_example.shape

(3, 2, 4)

In [15]:
a = np.arange(6)
print(a)

[0 1 2 3 4 5]


In [16]:
b = a.reshape(3, 2)
print(b)

[[0 1]
 [2 3]
 [4 5]]


In [17]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [18]:
a2 = a[np.newaxis, :]
a2.shape

(1, 6)

In [19]:
row_vector = a[np.newaxis, :]
row_vector.shape

(1, 6)

In [20]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [21]:
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [22]:
b = np.expand_dims(a, axis=1)
b.shape

(6, 1)

In [23]:
c = np.expand_dims(a, axis=0)
c.shape

(1, 6)

In [24]:
data = np.array([1, 2, 3])

data[1]

2

In [25]:
data[-2:]

array([2, 3])

In [26]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
c = a[(a > 2) & (a < 11)]
print(c)

[ 3  4  5  6  7  8  9 10]


In [29]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b = np.nonzero(a < 5)
print(b)

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [31]:
list_of_coordinates= list(zip(b[0], b[1]))

for coord in list_of_coordinates:
    print(coord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [32]:
print(a[b])

[1 2 3 4]


In [33]:
a1 = np.array([[1, 1],
                [2, 2]])

a2 = np.array([[3, 3],
                [4, 4]])

In [34]:
np.vstack((a1, a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [35]:
np.hstack((a1, a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [36]:
x = np.arange(1, 25).reshape(2, 12)
x

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [37]:
np.hsplit(x, 3)

[array([[ 1,  2,  3,  4],
        [13, 14, 15, 16]]),
 array([[ 5,  6,  7,  8],
        [17, 18, 19, 20]]),
 array([[ 9, 10, 11, 12],
        [21, 22, 23, 24]])]

In [38]:
data = np.array([1, 2])
ones = np.ones(2, dtype=int)
data + ones

array([2, 3])

In [39]:
data - ones

array([0, 1])

In [40]:
data * data

array([1, 4])

In [41]:
data / data

array([1., 1.])

In [42]:
a = np.array([1, 2, 3, 4])

a.sum()

10

In [43]:
data = np.array([1.0, 2.0])
data * 1.6

array([1.6, 3.2])

In [44]:
data.max()

2.0

In [45]:
data.min()

1.0

In [46]:
data.sum()

3.0

In [47]:
rng = np.random.default_rng(0)
rng.random(3)

array([0.63696169, 0.26978671, 0.04097352])

In [48]:
rng.random((3, 2))

array([[0.01652764, 0.81327024],
       [0.91275558, 0.60663578],
       [0.72949656, 0.54362499]])

In [49]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])
unique_values = np.unique(a)
print(unique_values)

[11 12 13 14 15 16 17 18 19 20]


In [50]:
arr = np.arange(6)
arr.transpose()

array([0, 1, 2, 3, 4, 5])

In [51]:
arr.transpose()

array([0, 1, 2, 3, 4, 5])

In [52]:
arr = np.arange(6).reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [53]:
arr.transpose()

array([[0, 3],
       [1, 4],
       [2, 5]])

In [54]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
reversed_arr = np.flip(arr)
print('Reversed Array: ', reversed_arr)

Reversed Array:  [8 7 6 5 4 3 2 1]
